/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    ContractsList: typeof import('./src/components/Users/components/contractsList.vue')['default']
    DataTable: typeof import('./src/components/dataTable/DataTable.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    UserAdd: typeof import('./src/components/Users/components/userAdd.vue')['default']
    UserContracts: typeof import('./src/components/Users/components/userContracts.vue')['default']
    UserDetails: typeof import('./src/components/Users/components/userDetails.vue')['default']
    UserEdit: typeof import('./src/components/Users/components/userEdit.vue')['default']
    UsersList: typeof import('./src/components/Users/usersList.vue')['default']
  }
}
